FROM anapsix/alpine-java
ADD target/LocalAsyncStreamPipelineServer-1.0-SNAPSHOT.jar /home/LocalAsyncStreamPipelineServer-1.0-SNAPSHOT.jar
ADD startup_services.sh /home/startup_services.sh
CMD /home/startup_services.sh
